"""Shared participant-PDF helpers for the all-channel EEG pipeline.

The existing analysis/utils/pdf_report.py ParticipantPDF class is deliberately
reused so the all-channel stages append to the same persistent participant report
mechanism as EEG_posterior_channels. Each call rebuilds the PDF from its JSON
manifest, which means later preprocessing stages cannot erase earlier pages.
"""
from __future__ import annotations

import sys
from pathlib import Path

# EEG_all_channels -> subject -> analysis. Add analysis/utils so we reuse the
# same ParticipantPDF implementation as the posterior-channel pipeline.
HERE = Path(__file__).resolve().parent
ANALYSIS_DIR = HERE.parents[1]
UTILS_DIR = ANALYSIS_DIR / "utils"
if str(UTILS_DIR) not in sys.path:
    sys.path.insert(0, str(UTILS_DIR))

from pdf_report import ParticipantPDF  # noqa: E402


def participant_report(project_root: Path, subject: str) -> ParticipantPDF:
    """Return the persistent PDF report object for one participant."""
    folder = project_root / "derivatives" / "reports" / f"sub-{subject}"
    return ParticipantPDF(str(folder), subject)


def figure_dir(project_root: Path, subject: str) -> Path:
    """Folder for figures specifically generated by all-channel QC."""
    out = project_root / "derivatives" / "figures" / f"sub-{subject}" / "EEG_all_channels"
    out.mkdir(parents=True, exist_ok=True)
    return out


def fmt_channels(channels) -> str:
    """Human-readable channel list for the PDF."""
    values = [str(ch) for ch in channels]
    return ", ".join(values) if values else "None"
