"""A03: manuscript-style summary derived from participant audit files."""
from __future__ import annotations
import argparse,json
from pipeline_config import qc_dir,resolve_project_root
from all_channel_report import participant_report,fmt_channels
def parse_args():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--subject',required=True);p.add_argument('--platform',choices=['mac','bluebear'],default='mac');p.add_argument('--project-root',default=None);return p.parse_args()
def read_json(path):return json.loads(path.read_text(encoding='utf-8')) if path.exists() else {}
def main():
 a=parse_args();s=a.subject.removeprefix('sub-');root=resolve_project_root(a.platform,a.project_root);q=qc_dir(root,s);report=participant_report(root,s);p01=read_json(q/'P01_pyprep_segment_epoch_reref.json');p02=read_json(q/'P02_ica_decisions.json');p03=read_json(q/'P03_manual_epoch_rejection.json');erp=read_json(q/'A01_erp_analysis.json');tfr=read_json(q/'A02_tfr_analysis.json');ref='average EEG reference' if p01.get('rereference')=='avg' else 'original reference (no rereferencing)';final_bad=p03.get('final_bad_channels',p01.get('bad_channels',[]));erp_roi=erp.get('roi_final',[]);tfr_roi=tfr.get('roi_final',[]);erp_candidates=erp.get('roi_candidates_predefined',['PO3','POz','PO4','O1','Oz','O2','PO7','PO8']);tfr_candidates=tfr.get('roi_candidates_predefined',erp_candidates)
 text=(f'Continuous EEG was band-pass filtered from {p01.get("high_pass_hz",1):g} to {p01.get("low_pass_hz",100):g} Hz before PyPREP and manual channel-quality assessment. Final bad channels were {fmt_channels(final_bad)}. Stimulation and no-stimulation periods were segmented using the predefined timing table; cue epochs extended from -0.5 to +1.6 s with baseline=None and detrend=1, followed by {ref}. '
 f'FastICA was fitted to concatenated stimulation and no-stimulation epochs using a 1-40 Hz, 200-Hz fitting copy; component maps and source time series were inspected together and the fitted solution was applied separately to the original condition epochs. ICA-cleaned epochs were manually inspected for bad trials and additional bad channels. Final Welch PSD QC covered 0.1 Hz to the lower of 100 Hz or Nyquist; stimulation-artifact QC overlaid stimulation and no-stimulation mean PSDs and was diagnostic only. '
 f'ERPs combined attention-left/right trials within condition, used trial averaging, a {erp.get("evoked_low_pass_hz",30):g}-Hz low-pass, baseline {erp.get("baseline_s",[-.1,0])}, and display window {erp.get("erp_display_window_s",[-.1,.5])} s. All common good sensors were shown in scalp layout. Separate posterior/occipital channels were {fmt_channels(erp_candidates)}. Final channels contributing to the ERP ROI mean: {fmt_channels(erp_roi)}. '
 f'TFR power combined attention-left/right trials and used multitaper 2-30 Hz in 1-Hz steps, n_cycles=frequency/2, time-bandwidth={tfr.get("time_bandwidth",2):g}, FFT=True, ITC=False, trial averaging=True and decim={tfr.get("decim",2)}. Stim/no-stim displays used percent baseline {tfr.get("condition_baseline_s",[-.3,-.1])}; difference and normalized difference used unbaselined power with no baseline correction. All common good sensors were shown in scalp layout. Separate posterior/occipital channels were {fmt_channels(tfr_candidates)}. Final channels contributing to the TFR ROI mean: {fmt_channels(tfr_roi)}.')
 report.add_text('Participant EEG analysis: methods summary',text,'Analysis overview (manuscript style)');print(f'Analysis overview added for sub-{s}: {report.pdf_fname}')
if __name__=='__main__':main()
